spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://MSI:1433;databaseName=ServicePedagogiqueDB;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Passw0rd}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

app.security.jwt.secret=${JWT_SECRET:change-this-dev-secret-before-production-gestion-service-pedagogique}
app.security.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:120}
